services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: raina
      RABBITMQ_DEFAULT_PASS: raina

  workspace-service:
    build:
      context: ..
      dockerfile: services/workspace-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ../services/workspace-service/.env.example
    depends_on:
      - rabbitmq
    ports:
      - "8010:8010"

  notification-service:
    build:
      context: ..
      dockerfile: services/notification-service/Dockerfile
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - "8016:8016"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password

      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  passport-service:
    build:
      context: ..
      dockerfile: services/passport-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ../services/passport-service/.env.example
    ports:
      - "8020:8020"
    depends_on:
      - keycloak

  sentinel-service:
    build:
      context: ..
      dockerfile: services/sentinel-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ../services/sentinel-service/.env.example
    ports:
      - "8030:8030"

volumes:
  postgres_data:
    name: keycloak_postgres_data
  mongo_data:
    name: sentinel_mongo_data